export const ADMIRAL_ALERT_PREFIX = 'ICSN ADMIRAL // ';
export const DEFAULT_FLEET_ALERT_MESSAGE =
  `${ADMIRAL_ALERT_PREFIX}RED ALERT // WOLF ATTACK IMMINENT ALL HANDS TO BATTLE STATIONS. NON-CREW MUST SHELTER IN PLACE UNTIL ALERT LIFTED`;
export const MAX_FLEET_ALERT_LENGTH = 500;
