import { describe, it, expect } from 'vitest';
import { createCastingCommands } from './castingCompanionCallable';
import type { Firestore, Transaction } from 'firebase-admin/firestore';
const now=1800000000000;
const schema={title:'Synthetic casting',description:'',sections:[{title:'Names',questions:[{id:'name',label:'Name',type:'short',required:true}]}]};
function fixture() {
 const docs=new Map<string,Record<string,unknown>>([
 ['sessions/lobby',{phase:'lobby',currentTurn:0}],['sessions/lobby/players/gm',{role:'gm',connected:true,lastSeenAt:now}],['sessions/lobby/gmInstances/device',{uid:'gm',connected:true,lastSeenAt:now}],['gmAccess/gm',{authenticatedAt:now-1000}],
 ]);let authorityCalls=0;
 const snapshot=(path:string)=>({exists:docs.has(path),id:path.split('/').at(-1),get:(key:string)=>docs.get(path)?.[key],data:()=>structuredClone(docs.get(path))});
 const db={doc:(path:string)=>({path}),runTransaction:async(run:(tx:unknown)=>Promise<unknown>)=>{const writes: (()=>void)[]=[];const tx={get:async(ref:{path:string})=>snapshot(ref.path),set:(ref:{path:string},data:Record<string,unknown>)=>writes.push(()=>docs.set(ref.path,structuredClone(data))),create:(ref:{path:string},data:Record<string,unknown>)=>writes.push(()=>{if(docs.has(ref.path))throw new Error('exists');docs.set(ref.path,structuredClone(data));})};const result=await run(tx);for(const write of writes)write();return result;}};
 const requireGm=async(tx:Transaction,sessionId:string,uid:string,instanceId:string)=>{authorityCalls++;const session=await tx.get(db.doc(`sessions/${sessionId}`) as never),player=await tx.get(db.doc(`sessions/${sessionId}/players/${uid}`) as never),instance=await tx.get(db.doc(`sessions/${sessionId}/gmInstances/${instanceId}`) as never);if(player.get('role')!=='gm'||instance.get('uid')!==uid)throw Object.assign(new Error('denied'),{code:'permission-denied'});return {session,player,instance};};
 const commands=createCastingCommands({db:db as unknown as Firestore,requireGm,verifyIdentity:async(request:{auth?:{uid:string}})=>{if(!request.auth)throw Object.assign(new Error('signed out'),{code:'unauthenticated'});return request.auth.uid;},now:()=>now,emulator:false});
 const call=(operation:string,payload:Record<string,unknown>,uid:string|undefined='gm',extra={})=>commands.handle({data:{operation,payload,instanceId:'device'},...(uid?{auth:{uid}}:{}),app:{appId:'verified-fixture'},...extra});
 return {docs,call,authorityCalls:()=>authorityCalls};
}
describe('actual casting callable Firestore path',()=>{
 it('writes durable lobby binding and immutable publication, no game start',async()=>{const f=fixture();const workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});expect(f.docs.get(`castingWorkspaces/${workspace}`)?.sessionId).toBe('lobby');expect(f.docs.get('sessions/lobby')?.phase).toBe('lobby');expect(f.authorityCalls()).toBeGreaterThan(0);
 const form=await f.call('createForm',{workspace,definition:schema,attempt:'form'}) as {id:string};const published=await f.call('publish',{workspace,formId:form.id,expectedRevision:1,attempt:'publish'}) as {handle:string};expect(await f.call('publicForm',{handle:published.handle},undefined)).toEqual({definition:schema,version:1});expect([...f.docs.keys()].some(p=>p.startsWith('castingPublishedHandles/'))).toBe(true);});
 it('nonGM cross-session and revoked access fail before reads writes and historical acknowledgements',async()=>{const f=fixture();const workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});f.docs.get('sessions/lobby/players/gm')!.role='player';await expect(f.call('workspace',{workspace})).rejects.toMatchObject({code:'permission-denied'});f.docs.get('sessions/lobby/players/gm')!.role='gm';f.docs.delete('gmAccess/gm');await expect(f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'})).rejects.toMatchObject({code:'permission-denied'});});
 it('requires genuine callable AppCheck before any database access and rejects forged UID fields',async()=>{const f=fixture();await expect(f.call('workspace',{workspace:'w'.repeat(32)},'gm',{app:undefined})).rejects.toMatchObject({code:'failed-precondition'});expect(f.authorityCalls()).toBe(0);await expect(f.call('workspace',{workspace:'w'.repeat(32),uid:'forged'})).rejects.toMatchObject({code:'invalid-argument'});});
});
it('real handler scopes submit receipts to Auth UID and charges publication/UID budgets only once',async()=>{
 const f=fixture(),workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});const form=await f.call('createForm',{workspace,definition:schema,attempt:'form'}) as {id:string};const publication=await f.call('publish',{workspace,formId:form.id,expectedRevision:1,attempt:'publish'}) as {handle:string};const submit={handle:publication.handle,version:1,answers:{name:'Synthetic'},attempt:'a'.repeat(32)};
 const response=await f.call('submit',submit,'respondent');expect(await f.call('submit',submit,'respondent')).toEqual(response);expect(await f.call('submit',submit,'other-respondent')).not.toEqual(response);await expect(f.call('submit',{...submit,answers:{name:'Changed'}},'respondent')).rejects.toMatchObject({code:'already-exists'});
 for(let n=1;n<20;n++)await f.call('submit',{...submit,attempt:String(n).padStart(32,'b')},'respondent');await expect(f.call('submit',{...submit,attempt:'z'.repeat(32)},'respondent')).rejects.toMatchObject({code:'resource-exhausted'});expect(await f.call('submit',submit,'respondent')).toEqual(response);
});
it('retired form indexes remain inactive after old publish acknowledgement replay and session deletion',async()=>{
 const f=fixture(),workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});const form=await f.call('createForm',{workspace,definition:schema,attempt:'form'}) as {id:string};const request={workspace,formId:form.id,expectedRevision:1,attempt:'publish'};const published=await f.call('publish',request) as {handle:string};await f.call('unpublish',{workspace,formId:form.id,expectedRevision:2,attempt:'unpublish'});expect(await f.call('publish',request)).toEqual(published);await expect(f.call('publicForm',{handle:published.handle},undefined)).rejects.toMatchObject({code:'not-found'});
 const next=await f.call('publish',{workspace,formId:form.id,expectedRevision:3,attempt:'next'}) as {handle:string};f.docs.delete('sessions/lobby');await expect(f.call('publicForm',{handle:next.handle},undefined)).rejects.toMatchObject({code:'not-found'});
});
it('capacity failure rolls back serialized state, indexes and counters',async()=>{
 const f=fixture(),workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});const root=f.docs.get(`castingWorkspaces/${workspace}`)!;const state=JSON.parse(root.stateJson as string) as {templates:unknown[]};for(let n=0;n<70;n++)state.templates.push([`template-${n}`,{id:`template-${n}`,workspace,name:'Synthetic',details:'x'.repeat(9500)}]);root.stateJson=JSON.stringify(state);const before=structuredClone([...f.docs]);
 const large={title:'Large',description:'x'.repeat(10000),sections:[{title:'Options',questions:[{id:'q',label:'Large choice',type:'dropdown',required:false,options:Array.from({length:100},(_,n)=>String(n).padStart(500,'x'))}]}]};await expect(f.call('createForm',{workspace,definition:large,attempt:'large'})).rejects.toMatchObject({code:'resource-exhausted'});expect([...f.docs]).toEqual(before);
});

it('unpublishes at capacity and preserves retry/conflict safety with private durable receipts',async()=>{
 const f=fixture(),workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});const form=await f.call('createForm',{workspace,definition:schema,attempt:'form'}) as {id:string};const published=await f.call('publish',{workspace,formId:form.id,expectedRevision:1,attempt:'publish'}) as {handle:string};
 const root=f.docs.get(`castingWorkspaces/${workspace}`)!;const state=JSON.parse(root.stateJson as string);state.templates.push(['padding',{id:'padding',workspace,name:'Synthetic',details:''}]);let raw=JSON.stringify(state);state.templates.at(-1)[1].details='x'.repeat(700*1024-Buffer.byteLength(raw));root.stateJson=JSON.stringify(state);expect(Buffer.byteLength(root.stateJson as string)).toBe(700*1024);
 const request={workspace,formId:form.id,expectedRevision:2,attempt:'r'.repeat(200)};const result=await f.call('unpublish',request);expect(await f.call('unpublish',request)).toEqual(result);await expect(f.call('unpublish',{...request,expectedRevision:3})).rejects.toMatchObject({code:'already-exists'});await expect(f.call('publicForm',{handle:published.handle},undefined)).rejects.toMatchObject({code:'not-found'});expect(Buffer.byteLength(f.docs.get(`castingWorkspaces/${workspace}`)!.stateJson as string)).toBeLessThanOrEqual(700*1024);
});

it('revokes a dossier at capacity without deleting retained answers, and rechecks authority on receipt replay',async()=>{
 const f=fixture(),workspace='w'.repeat(32);await f.call('bindWorkspace',{workspace,sessionId:'lobby',attempt:'bind'});const form=await f.call('createForm',{workspace,definition:schema,attempt:'form'}) as {id:string};const published=await f.call('publish',{workspace,formId:form.id,expectedRevision:1,attempt:'publish'}) as {handle:string};const response=await f.call('submit',{handle:published.handle,version:1,answers:{name:'Synthetic'},attempt:'s'.repeat(32)},'respondent') as {id:string};
 const template=await f.call('createTemplate',{workspace,template:{name:'Pilot',details:''},attempt:'template'}) as {id:string};const instance=await f.call('createInstance',{workspace,templateId:template.id,details:{playerName:'Synthetic',characterName:'Pilot',details:'Synthetic details'},attempt:'instance'}) as {id:string};const share=await f.call('assign',{workspace,responseId:response.id,instanceId:instance.id,expectedResponseRevision:1,expectedInstanceRevision:1,attempt:'assign'}) as {handle:string};
 const root=f.docs.get(`castingWorkspaces/${workspace}`)!;const state=JSON.parse(root.stateJson as string);state.templates.push(['padding',{id:'padding',workspace,name:'Synthetic',details:''}]);state.templates.at(-1)[1].details='x'.repeat(700*1024-Buffer.byteLength(JSON.stringify(state)));root.stateJson=JSON.stringify(state);const retained=structuredClone(state.responses[0][1].answers);
 const request={workspace,responseId:response.id,expectedResponseRevision:2,attempt:'r'.repeat(200)};const result=await f.call('revoke',request);expect(await f.call('revoke',request)).toEqual(result);await expect(f.call('revoke',{...request,expectedResponseRevision:3})).rejects.toMatchObject({code:'already-exists'});await expect(f.call('dossier',{handle:share.handle},undefined)).rejects.toMatchObject({code:'not-found'});const saved=JSON.parse(f.docs.get(`castingWorkspaces/${workspace}`)!.stateJson as string);expect(saved.responses[0][1].answers).toEqual(retained);expect(saved.templates.at(-1)[1].details).toEqual(state.templates.at(-1)[1].details);expect([...f.docs.keys()].filter(path=>path.includes('/deactivationReceipts/'))).toHaveLength(1);f.docs.delete('gmAccess/gm');await expect(f.call('revoke',request)).rejects.toMatchObject({code:'permission-denied'});
});
