import { it, expect } from 'vitest';
import { createCastingFirebaseAdapter } from './adapter';
it('real adapter uses callable session prerequisite and immutable selected workspace, not synthetic fixture',async()=>{
 const calls: {name:string;payload:Record<string,unknown>}[]=[];const adapter=createCastingFirebaseAdapter({ensureIdentity:async()=>{},call:async(name:string,payload:Record<string,unknown>)=>{calls.push({name,payload});if(name==='claimGmInstance')return {};if(payload.operation==='prerequisite')return {gmAccessActive:true,sessions:[{id:'lobby',name:'Synthetic lobby',phase:'lobby',currentTurn:0,gmActive:true,instances:[{id:'device',name:'GM'}]}]};if(payload.operation==='bindWorkspace')return {workspace:'w'.repeat(32),sessionId:'lobby'};if(payload.operation==='workspace')return {forms:[],responses:[],templates:[],instances:[]};throw Error('unexpected callable');}});
 const prerequisite=await adapter.load!() as {prerequisite:{sessions:unknown[]}};expect(prerequisite.prerequisite.sessions).toHaveLength(1);await adapter.claimSessionGm({sessionId:'lobby',attempt:'device'});await adapter.load();await adapter.selectSession!({sessionId:'lobby',attempt:'select'});const loaded=await adapter.load!() as {accessMode:string;formSaved:boolean};expect(loaded.accessMode).toBe('gm-bearer');expect(loaded.formSaved).toBe(false);expect(calls.every(call=>['castingCompanionCommand','claimGmInstance'].includes(call.name))).toBe(true);expect(calls.some(call=>call.payload.operation==='workspace')).toBe(true);
});
it('auth reset drops private workspace and late command replies',async()=>{
 let resolve:((value:unknown)=>void)|undefined;const adapter=createCastingFirebaseAdapter({workspace:'w'.repeat(32),instanceId:'device',ensureIdentity:async()=>{},call:()=>new Promise(done=>{resolve=done;})});const pending=adapter.load!();const rejection=expect(pending).rejects.toMatchObject({code:'unauthenticated'});rejection.catch(()=>{});await Promise.resolve();await adapter.resetAuthority!();resolve?.({forms:[],responses:[{private:'Synthetic'}],templates:[],instances:[]});await rejection;
});
it('does not adopt or renew a sibling tab GM instance',async()=>{
 const calls:string[]=[];const adapter=createCastingFirebaseAdapter({ensureIdentity:async()=>{},call:async(name)=>{calls.push(name);return {gmAccessActive:true,sessions:[{id:'lobby',name:'Synthetic',phase:'lobby',currentTurn:0,gmActive:true,instances:[{id:'sibling',name:'Other browser'}]}]};}});
 const loaded=await adapter.load() as {prerequisite:{sessions:{gmActive:boolean}[]}};expect(loaded.prerequisite.sessions[0]!.gmActive).toBe(false);expect(adapter.getAuthority().instanceId).toBe('');await adapter.heartbeat();expect(calls).not.toContain('refreshPresence');await expect(adapter.selectSession({sessionId:'lobby',attempt:'select'})).rejects.toMatchObject({code:'unauthenticated'});
});
it('heartbeat validates current casting authority after renewing presence',async()=>{
 const calls:string[]=[];const adapter=createCastingFirebaseAdapter({workspace:'w'.repeat(32),instanceId:'this-tab',ensureIdentity:async()=>{},call:async(_name,payload)=>{calls.push(String(payload.operation));if(payload.operation==='prerequisite')return {gmAccessActive:true,sessions:[{id:'lobby',name:'Synthetic',phase:'lobby',currentTurn:0,gmActive:true,instances:[{id:'this-tab',name:'GM'}]}]};if(payload.operation==='workspace'&&calls.filter(x=>x==='workspace').length>1)throw Object.assign(new Error('expired GM access'),{code:'functions/permission-denied'});return {forms:[],responses:[],templates:[],instances:[]};}});
 await adapter.load();await expect(adapter.heartbeat()).rejects.toMatchObject({code:'permission-denied'});expect(calls.filter(x=>x==='workspace')).toHaveLength(2);
});
